# Generated by Django 5.0.2 on 2024-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='imgname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='img',
            field=models.ImageField(upload_to='files/imagess'),
        ),
    ]
