# Generated by Django 5.0.2 on 2024-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_imagedata_imgname_alter_imagedata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='img',
            field=models.ImageField(max_length=300, null=True, upload_to='images/'),
        ),
    ]
